name: sip_ua
version: 1.0.0
description: A SIP UA stack for Flutter/Dart, based on flutter-webrtc, support iOS/Android/Destkop/Web.
homepage: https://github.com/cloudwebrtc/dart-sip-ua
environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  collection: ^1.18.0
  crypto: ^3.0.3
  flutter_webrtc: ^0.10.4
  intl: ^0.19.0
  logger: ^2.0.2+1
  path: ^1.6.4
  random_string: ^2.3.1
  recase: ^4.1.0
  sdp_transform: ^0.3.2
  text: ^0.2.0
  uuid: ^4.2.1


dev_dependencies:
  import_sorter: ^4.6.0
  lints: ^3.0.0
  test: any
